### ISSUE TITLE
Do not remove duplicate header fields

### ISSUE THREAD

**Issue by sol** [zalora/sproxy#16]
Currently we discard duplicate header fields.  According to the RFC 2616, duplicate header fields are permissible:

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)].

(http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

**Comment by ip1981** [comment]
Done in https://github.com/zalora/sproxy/commit/8f86c4976632dafaec4fcb57a16a05a25a7c9401
