### ISSUE TITLE
Should it be possible to have multiple privileges for any given domain/path/method in privilege_rule?

### ISSUE THREAD

**Issue by cimmanon** [zalora/sproxy#57]
Currently, the primary key for privilege_rule is (domain, privilege, path, method).  What this means is that it is possible for there to be multiple privileges to exist for any given domain/path/method combination:

```
   domain   | privilege | path | method
----------------------------------------
example.com | foo       | /x   | %
example.com | bar       | /x   | %
```

Is there a legitimate reason for this to be allowed?

If the answer is **no**, then the primary key should be changed to (domain, path, method).  If there's already duplicate data preventing the change in the primary key, we'll need to decide how to fix it.

If the answer is **yes**, then our authentication query needs to be modified to support this behavior.

Why is this a problem?  The use of `limit 1` in our subquery will pick out only 1 of the valid privileges as the *correct* one and all others will be considered to be invalid.  For example, if Bob only has privilege to foo and Joe only has privilege to bar, then only one of these guys will not be able to access the page (and the one who has permissions might even be different from request to request).

**Comment by ip1981** [comment]
https://github.com/zalora/sproxy/commit/29d831414bfe031212f5df2f1e15760344133b43
