### ISSUE TITLE
Client parsing failures should not count as errors.

### ISSUE THREAD

**Issue by shlevy** [zalora/sproxy#68]
I'm seeing a bunch of messages like

> ERROR ThreadId 30062: TLSException (HandshakeFailed (Error_Packet_Parsing "deprecatedheader: parsing error: remaining bytes"))

with priority `3`, i.e. error. IMO an error should represent an exceptional situation or a bug in the code, whereas a web-facing tool like sproxy should consider malformed requests part of normal operation.

**Comment by sol** [comment]
Patches welcome ;)

**Comment by ip1981** [comment]
Done in https://github.com/zalora/sproxy/commit/d77c29d9b6281d2b243ddf4f0b1c02f66d998948.
