### ISSUE TITLE
Provide automatic robots.txt

### ISSUE THREAD

**Issue by jekor** [zalora/sproxy#70]
Since anything proxied by sproxy is by definition non-public, it makes sense to automatically exclude robots by responding to a /robots.txt request from within sproxy itself with:

```
User-agent: *
Disallow: /
```

This prevents bots from indexing Google OAuth login pages.

I can't think of any reason you'd want a proxied site to provide its own robots.txt, but in case that need exists, we could make the behavior optional.

**Comment by ip1981** [comment]
https://github.com/zalora/sproxy/commit/d039fcb31a86290b8b76e0a82e08628781646e69
